from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
  path('index',views.index),
  path('',views.index ),
  path('contact', views.contact),
  path('about', views.about),
  path('blog', views.blog),
  path('classes', views.classes),
  path('feature', views.feature),
  path('login', views.login),
  path('logout', views.logout),
  path('signup', views.signup),
  path('adminbase', views.adminbase),
  path('userbase', views.userbase),
  path('adminuserlist', views.adminuserlist),
  path('adminuserdelete', views.adminuserdelete),
  path('addstaff', views.addstaff),
  path('adminclass', views.adminclass),
  path('addequip', views.addequip),
  path('userprofileview', views.userprofileview),
  path('adminstaffview', views.adminstaffview),
  path('adminviewequip', views.adminviewequip),
  path('addclass', views.addclass),
  path('adminclassview', views.adminclassview),
  path('userclassview', views.userclassview),
  path('userenrollclass', views.userenrollclass),
  path('enrollclassview', views.enrollclassview),
  path('userequipview', views.userequipview),
  path('userequipbook', views.userequipbook),
  path('userfeedback', views.userfeedback),
  path('classbookingsview', views.classbookingsview),
  path('usereqbookview', views.usereqbookview),
  path('admineqbookview', views.admineqbookview),
  path('adminfeedbackview', views.adminfeedbackview),
  path('userproupdate/<int:id>',views.userproupdate,name="userproupdate"),
  path('userproupdate/userprofileupdate/<int:id>',views.userprofileupdate,name="userprofileupdate"),
  path('adminstaffupdates/<int:id>',views.adminstaffupdates,name="adminstaffupdates"),
  path('adminstaffupdates/adminstaffupdate/<int:id>',views.adminstaffupdate,name="adminstaffupdate"),
  path('adminclassupdates/<int:id>', views.adminclassupdates,name="adminclassupdates"),
  path('adminclassupdates/adminclassupdate/<int:id>', views.adminclassupdate,name="adminclassupdate"),
  path('adminequpdates/<int:id>',views.adminequpdates,name="adminequpdates"),
  path('adminequpdates/adminequpdate/<int:id>',views.adminequpdate,name="adminequpdate"),
  path('adminstaffdelete/<int:id>',views.adminstaffdelete,name="adminstaffdelete"),
  path('adminclassdelete/<int:id>',views.adminclassdelete,name="adminclassdelete"),
  path('userclassenrolldelete/<int:id>',views.userclassenrolldelete,name="userclassenrolldelete"),
  path('admineqdelete/<int:id>',views.admineqdelete,name="admineqdelete"),
  path('adminuserdelete/<int:id>',views.adminuserdelete,name="adminuserdelete"),
  path('usereqbookdelete/<int:id>',views.usereqbookdelete,name="usereqbookdelete"),
  path('adminclassbookingdelete/<int:id>',views.adminclassbookingdelete,name="adminclassbookingdelete"),
  path('admineqbookdelete/<int:id>',views.admineqbookdelete,name="admineqbookdelete"),
  path('adminfeedbackdelete/<int:id>',views.adminfeedbackdelete,name="adminfeedbackdelete"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)