# Generated by Django 4.2.12 on 2024-05-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userphoto', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('useremail', models.CharField(max_length=200)),
                ('userpass', models.CharField(max_length=200)),
            ],
        ),
    ]
