# Generated by Django 4.2.12 on 2024-05-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffphoto', models.CharField(max_length=200)),
                ('staffname', models.CharField(max_length=200)),
                ('staffspec', models.CharField(max_length=300)),
            ],
        ),
    ]
