# Generated by Django 4.2.12 on 2024-05-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_eqdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='classdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffnames', models.CharField(max_length=200)),
                ('staffspecs', models.CharField(max_length=200)),
                ('classtime', models.CharField(max_length=100)),
                ('classdate', models.CharField(max_length=30)),
            ],
        ),
    ]
