# Generated by Django 4.2.12 on 2024-05-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_classdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrollclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('staffnames', models.CharField(max_length=200)),
                ('staffspecs', models.CharField(max_length=200)),
                ('classtime', models.CharField(max_length=100)),
                ('classdate', models.CharField(max_length=30)),
            ],
        ),
    ]
