# Generated by Django 4.2.12 on 2024-05-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_enrollclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
    ]
