# Generated by Django 4.2.12 on 2024-05-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='eqbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('eqnames', models.CharField(max_length=200)),
                ('classtime', models.CharField(max_length=100)),
            ],
        ),
    ]
